name: "Is it nice PR?"
on:
  pull_request:
    types:
      - opened
    branches:
        - main

jobs:
  nicepr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: nice pr?
        uses: './ts/create-gh-actions'